services:
    staffit.banlist.controller:
        class: staffit\banlist\controller\main
        arguments:
            - @dbal.conn
            - @user
            - @config
            - @controller.helper
            - @template
    staffit.banlist.listener:
        class: staffit\banlist\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @dbal.conn
        tags:
            - { name: event.listener }
